### PR TITLE
added tomcat-user.xml

### PR DESCRIPTION
**Pull request by spcags**
Hello there, 
Thank you very much for your work. 
I was assigned to work with a project using DSpace-cris-6RC2. I am new to DSpace related. 
It took me a few days to learn how to compile the code with a lot of the issues...  So frustrated... 
then by accident, I found this repo and so happy that this could save me... 
But then I could not build the image... 

missing: tomcat-users.xml,   ./fs, wait-for-postgres.sh etc. 

So please check in the necessary files etc so that someone like me can build a docker image without
any problems.

Please DO NOT take my comments above NEGATIVELY. I DO understand that it is open source 
and free and I DO NOT have any rights to complain anything... 

Thank you! 

Huaxiao Wang 
Beijing, China

### CODE REVIEW

**Comment by firecyberice** [comment]
There is already a PR which adds these files please have a look at  #2.

**Comment by abollini** [comment]
Hi @spcags ,
I have merged the PR #2 provided by @firecyberice 
Please check and confirm that it solves your issue.
Feel free to ask for help in setup DSpace-CRIS on the public DSpace mailing lists / slack channels (https://wiki.duraspace.org/display/DSPACE/Mailing+Lists) or writing directly to me (andrea.bollini _AT_ 4science.it)

**Comment by spcags** [comment]
Hi @abollini , 
Thanks a lot. It works perfectly! It built and started running...

**Comment by spcags** [comment]
fixed.

**Pull request closed without merging**
